OANDA:
  LIVE_API: "api-fxtrade.oanda.com"
  LIVE_ACCESS_TOKEN: "XXXXXXXXXXXXXXXXXXXXXXX"
  PRACTICE_API: "api-fxpractice.oanda.com"
  PRACTICE_ACCESS_TOKEN: "XXXXXXXXXXXXXXXXXXXXXXXXXX"
  DEFAULT_ACCOUNT_ID: "XXXXXXXXXXXXXXXXXXXXXXXX"
  PORT: 443